Search.appendIndex(
    [
                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource",
            "name": "BaseResource",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "BaseResource\u0020constructor.",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003AsetToken\u0028\u0029",
            "name": "setToken",
            "summary": "Set\u0020Autentique\u0020API\u0020Token\u0020but\u0020by\u0020default\u0020it\u0020will\u0020get\u0020from\u0020\u0024_ENV\u005B\u0022AUTENTIQUE_TOKEN\u0022\u005D",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method_setToken"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003AsetSandbox\u0028\u0029",
            "name": "setSandbox",
            "summary": "Set\u0020Autentique\u0020Sandbox\u0020Mode\u0020but\u0020by\u0020default\u0020it\u0020will\u0020get\u0020from\u0020\u0024_ENV\u005B\u0022AUTENTIQUE_SANDBOX\u0022\u005D",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method_setSandbox"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003AsetApi\u0028\u0029",
            "name": "setApi",
            "summary": "Set\u0020Api\u0020instance\u0020customizing\u0020the\u0020Autentique\u0020API\u0020URL\u0020and\u0020Request\u0020Timeout",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method_setApi"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Get\u0020Autentique\u0020API\u0020Token",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method_getToken"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003AgetSandbox\u0028\u0029",
            "name": "getSandbox",
            "summary": "Get\u0020Autentique\u0020Sandbox\u0020Mode",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method_getSandbox"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003AgetApi\u0028\u0029",
            "name": "getApi",
            "summary": "Get\u0020Autentique\u0020API",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#method_getApi"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003A\u0024autentiqueUrl",
            "name": "autentiqueUrl",
            "summary": "Autentique\u0020API\u0020URL",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#property_autentiqueUrl"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003A\u0024api",
            "name": "api",
            "summary": "Autentique\u0020API",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#property_api"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003A\u0024token",
            "name": "token",
            "summary": "Autentique\u0020API\u0020Token",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#property_token"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003A\u0024sandbox",
            "name": "sandbox",
            "summary": "Autentique\u0020Sandbox\u0020Mode",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#property_sandbox"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\BaseResource\u003A\u003A\u0024resourcesEnum",
            "name": "resourcesEnum",
            "summary": "Autentique\u0020Resources\u0020Enum",
            "url": "classes/vinicinbgs-Autentique-BaseResource.html#property_resourcesEnum"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents",
            "name": "Documents",
            "summary": "Class\u0020Documents",
            "url": "classes/vinicinbgs-Autentique-Documents.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Documents\u0020constructor.",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AlistAll\u0028\u0029",
            "name": "listAll",
            "summary": "List\u0020all\u0020documents",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_listAll"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AlistById\u0028\u0029",
            "name": "listById",
            "summary": "List\u0020document\u0020by\u0020id",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_listById"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020Document",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_create"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020Document",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_update"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AsignById\u0028\u0029",
            "name": "signById",
            "summary": "Sign\u0020document\u0020by\u0020id",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_signById"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AdeleteById\u0028\u0029",
            "name": "deleteById",
            "summary": "Delete\u0020document\u0020by\u0020id",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_deleteById"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AmoveToFolder\u0028\u0029",
            "name": "moveToFolder",
            "summary": "Move\u0020document\u0020to\u0020folder",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_moveToFolder"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AmoveToFolderByFolder\u0028\u0029",
            "name": "moveToFolderByFolder",
            "summary": "Move\u0020document\u0020from\u0020folder\u0020to\u0020folder",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_moveToFolderByFolder"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AdeleteSigner\u0028\u0029",
            "name": "deleteSigner",
            "summary": "Delete\u0020signer\u0020from\u0020document",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_deleteSigner"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003AcreateSigner\u0028\u0029",
            "name": "createSigner",
            "summary": "Create\u0020signer\u0020to\u0020document",
            "url": "classes/vinicinbgs-Autentique-Documents.html#method_createSigner"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Documents\u003A\u003A\u0024query",
            "name": "query",
            "summary": "GraphQL\u0020Query",
            "url": "classes/vinicinbgs-Autentique-Documents.html#property_query"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum",
            "name": "ErrorMessagesEnum",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum\u003A\u003AERR_CONTENT_TYPE",
            "name": "ERR_CONTENT_TYPE",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html#constant_ERR_CONTENT_TYPE"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum\u003A\u003AERR_EMPTY_QUERY",
            "name": "ERR_EMPTY_QUERY",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html#constant_ERR_EMPTY_QUERY"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum\u003A\u003AERR_AUTENTIQUE_URL",
            "name": "ERR_AUTENTIQUE_URL",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html#constant_ERR_AUTENTIQUE_URL"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum\u003A\u003AERR_AUTENTIQUE_RESPONSE",
            "name": "ERR_AUTENTIQUE_RESPONSE",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html#constant_ERR_AUTENTIQUE_RESPONSE"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum\u003A\u003AERR_URL_INVALID",
            "name": "ERR_URL_INVALID",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html#constant_ERR_URL_INVALID"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ErrorMessagesEnum\u003A\u003AERR_TOKEN_EMPTY",
            "name": "ERR_TOKEN_EMPTY",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ErrorMessagesEnum.html#constant_ERR_TOKEN_EMPTY"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ResourcesEnum",
            "name": "ResourcesEnum",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ResourcesEnum.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ResourcesEnum\u003A\u003ADOCUMENTS",
            "name": "DOCUMENTS",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ResourcesEnum.html#constant_DOCUMENTS"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums\\ResourcesEnum\u003A\u003AFOLDERS",
            "name": "FOLDERS",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Enums-ResourcesEnum.html#constant_FOLDERS"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\BaseException",
            "name": "BaseException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-BaseException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\BaseException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-BaseException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\ContentTypeException",
            "name": "ContentTypeException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-ContentTypeException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\ContentTypeException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-ContentTypeException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyAutentiqueResponseException",
            "name": "EmptyAutentiqueResponseException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyAutentiqueResponseException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyAutentiqueResponseException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyAutentiqueResponseException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyAutentiqueUrlException",
            "name": "EmptyAutentiqueUrlException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyAutentiqueUrlException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyAutentiqueUrlException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyAutentiqueUrlException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyQueryException",
            "name": "EmptyQueryException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyQueryException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyQueryException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyQueryException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyTokenException",
            "name": "EmptyTokenException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyTokenException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\EmptyTokenException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-EmptyTokenException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\InvalidAutentiqueUrlException",
            "name": "InvalidAutentiqueUrlException",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-InvalidAutentiqueUrlException.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions\\InvalidAutentiqueUrlException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-exceptions-InvalidAutentiqueUrlException.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders",
            "name": "Folders",
            "summary": "Class\u0020Folders",
            "url": "classes/vinicinbgs-Autentique-Folders.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Documents\u0020constructor.",
            "url": "classes/vinicinbgs-Autentique-Folders.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003AlistAll\u0028\u0029",
            "name": "listAll",
            "summary": "List\u0020all\u0020folders",
            "url": "classes/vinicinbgs-Autentique-Folders.html#method_listAll"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003AlistById\u0028\u0029",
            "name": "listById",
            "summary": "List\u0020folder\u0020by\u0020id",
            "url": "classes/vinicinbgs-Autentique-Folders.html#method_listById"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003AlistContentsById\u0028\u0029",
            "name": "listContentsById",
            "summary": "List\u0020folder\u0020by\u0020id",
            "url": "classes/vinicinbgs-Autentique-Folders.html#method_listContentsById"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020folder",
            "url": "classes/vinicinbgs-Autentique-Folders.html#method_create"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003AdeleteById\u0028\u0029",
            "name": "deleteById",
            "summary": "Delete\u0020folder\u0020by\u0020id",
            "url": "classes/vinicinbgs-Autentique-Folders.html#method_deleteById"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Folders\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Folders.html#property_query"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api",
            "name": "Api",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_request"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003Aconnect\u0028\u0029",
            "name": "connect",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_connect"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_setUrl"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003AvalidateParams\u0028\u0029",
            "name": "validateParams",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_validateParams"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003ArequestJson\u0028\u0029",
            "name": "requestJson",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_requestJson"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003ArequestFormData\u0028\u0029",
            "name": "requestFormData",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_requestFormData"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003AgetErrorNo\u0028\u0029",
            "name": "getErrorNo",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_getErrorNo"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003AexecuteCurl\u0028\u0029",
            "name": "executeCurl",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_executeCurl"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "Get\u0020the\u0020value\u0020of\u0020url",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#method_getUrl"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003AACCEPT_CONTENTS",
            "name": "ACCEPT_CONTENTS",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#constant_ACCEPT_CONTENTS"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#property_url"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Api\u003A\u003A\u0024timeout",
            "name": "timeout",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Api.html#property_timeout"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query",
            "name": "Query",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Query\u0020constructor.",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#method___construct"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Get\u0020query",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#method_query"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003AformatQueryRemoveBrokenLine\u0028\u0029",
            "name": "formatQueryRemoveBrokenLine",
            "summary": "Format\u0020query\u0020to\u0020remove\u0020LF\u0020\u0028line\u0020feed\u0020\\n\u0029\u0020and\u0020CR\u0020\u0028carriege\u0020return\u0020\\r\u0029",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#method_formatQueryRemoveBrokenLine"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003AsetVariables\u0028\u0029",
            "name": "setVariables",
            "summary": "set\u0020Variables\u0020in\u0020query\u0020adding\u0020value",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#method_setVariables"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003ADIR",
            "name": "DIR",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#constant_DIR"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003A\u0024resource",
            "name": "resource",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#property_resource"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils\\Query\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/vinicinbgs-Autentique-Utils-Query.html#property_file"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique",
            "name": "Autentique",
            "summary": "",
            "url": "namespaces/vinicinbgs-autentique.html"
        },                {
            "fqsen": "\\vinicinbgs",
            "name": "vinicinbgs",
            "summary": "",
            "url": "namespaces/vinicinbgs.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/vinicinbgs-autentique-enums.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\exceptions",
            "name": "exceptions",
            "summary": "",
            "url": "namespaces/vinicinbgs-autentique-exceptions.html"
        },                {
            "fqsen": "\\vinicinbgs\\Autentique\\Utils",
            "name": "Utils",
            "summary": "",
            "url": "namespaces/vinicinbgs-autentique-utils.html"
        }            ]
);
